# Generated by Django 4.2 on 2024-09-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Сумма платежа, руб')),
                ('payment_purpose', models.CharField(max_length=128, verbose_name='Назначение платежа')),
                ('client_phone', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона')),
                ('client_email', models.EmailField(max_length=64, verbose_name='Email клиента')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
